# Render deployment configuration for Go Gin proxy
services:
  - type: web
    name: whm-proxy
    env: go
    region: oregon       # o asia, depende sa preference
    plan: free           # o standard, depende sa kailangan
    branch: main         # branch ng repo mo
    autoDeploy: true
    goVersion: 1.25.5
    buildCommand: go build -o app
    startCommand: ./app
    envVars:
      - key: PORT
        value: "8080"       # Render ay mag-ooverride nito sa runtime
   
